### ISSUE TITLE
status code 413: request entity too large

### ISSUE THREAD

**Issue by amaurymartiny** [saasify-sh/saasify#108]
Repro:

```bash
$ /Users/amaury/Workspace/reacher/webapp/node_modules/.bin/saasify deploy
parsing config saasify.json
✖ Creating deployment
Request failed with status code 413
request entity too large
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

The same saasify.json passed last week.

Version:
```
$ /Users/amaury/Workspace/reacher/webapp/node_modules/.bin/saasify -V
1.20.8
```

**Comment by transitive-bullshit** [comment]
Hey Amaury,

You're likely picking up some large files in the current directory (or a subdirectory) that are being considered part of the deployment.

Add a `.saasifyignore` file which has the same semantics as `.gitignore` to ensure that any unwanted files are not included when deploying.

**Comment by amaurymartiny** [comment]
Yes, cheers.
