### ISSUE TITLE
User validation failed: email: Path `email` is required.

### ISSUE THREAD

**Issue by bouiboui** [saasify-sh/saasify#14]
When I type `saasify signup`, and authenticate with Github, I get this message:

![image](https://user-images.githubusercontent.com/3274103/67278074-8eec5400-f4c8-11e9-93de-80645ec2dc61.png)

but the CLI displays:

```bash
$ saasify signup
- Authenticating with GitHub
× Authenticating with GitHub
Request failed with status code 400
User validation failed: email: Path `email` is required.
```

And then when I `init` a new project:

```bash
? Template? typescript
? Project Name (saasify-test)
? Project Name saasify-test
? Project Description (Powered by Saasify)
? Project Description Powered by Saasify
? Author's GitHub Handle (bouiboui)
? Author's GitHub Handle bouiboui
? GitHub Repo Path (bouiboui/saasify-test)
? GitHub Repo Path bouiboui/saasify-test
? License (MIT)
? License MIT
- Cloning "typescript" template
√ Cloning "typescript" template
- Copying "typescript" template to C:\Users\Julien\AppData\Local\Temp\saasify-test
√ Copying "typescript" template to C:\Users\Julien\AppData\Local\Temp\saasify-test
- Initializing git repo
× Initializing git repo
Command failed with exit code 1 (Unknown system error -1): git commit -m init typescript template (saasify@1.7.2)
```

The created folder is empty, so Git fails.

**Comment by mmedum** [comment]
Hi @bouiboui thanks for reporting this, I must admit that using my windows machine it does not seem to output any errors. Is this a standard windows 10 installation? Did the install of `saasify` go through without issues?

**Comment by bouiboui** [comment]
Previous message was at home, I tried it on my work machine too, same error, they are regular, updated Win10 machines. I tried it with node 10.15.1 (and got a compatibility warning, had to add --ignore-engines) and 9.10.0, same error.

**Comment by transitive-bullshit** [comment]
Hey @bouiboui, really sorry you're running into issues.

I honestly haven't tested at all on Windows, so I'm reaching out to a few developers who could possibly help repro the issue.

I think I may have resolved the `email` issue, as we were expecting GitHub to return an email for your account and I've now made that optional.

Would you mind running `saasify --version` and replying with the results?

Thanks!

**Comment by bouiboui** [comment]
```bash
$ saasify --version
1.7.2
```

**Comment by bouiboui** [comment]
It's... different! 😄 
```bash
$ saasify signup
- Authenticating with GitHub
× Authenticating with GitHub
Request failed with status code 409
Email "null" is unavailable
```

**Comment by bouiboui** [comment]
I don't know if that helps, but this is my e-mail setting in my Github profile:

![image](https://user-images.githubusercontent.com/3274103/67490433-86844c80-f673-11e9-922a-cc27423239a7.png)

**Comment by bouiboui** [comment]
Here are my full e-mail settings:

![image](https://user-images.githubusercontent.com/3274103/67491004-79b42880-f674-11e9-8286-15e944251fe7.png)

**Comment by PicchiKevin** [comment]
Here is what I did to make it work:

I had to uncheck `Keep my email addresses private`, on this page:
> ![image](https://user-images.githubusercontent.com/3274103/67491004-79b42880-f674-11e9-8286-15e944251fe7.png)

And then select a `primary email address`:
> ![image](https://user-images.githubusercontent.com/3274103/67490433-86844c80-f673-11e9-922a-cc27423239a7.png)

It works by doing this, but it doesn't feel like a normal behavior...

**Comment by transitive-bullshit** [comment]
Thanks for the short-term workaround @PicchiKevin. I agree that this shouldn't be required.

The `oauth` scope we're requesting during authentication is `email`, as it's the only piece of potentially non-public information that we're using to link users, so I'm not sure why this setting would affect that.

Investigating this further now and will follow up on this thread with a resolution.

Thanks!

**Comment by transitive-bullshit** [comment]
@PicchiKevin @bouiboui the email issue should now be resolved. You do not have to change your email preference settings, and if you previously did, you can change them back to be private.

This [StackOverflow answer](https://stackoverflow.com/questions/35373995/github-user-email-is-null-despite-useremail-scope/35387123) was very useful in fixing the issue.

@bouiboui if you're still having issues with `saasify init` on Windows, let's follow up on that in a separate issue.

**Comment by bouiboui** [comment]
```bash
$ saasify signup
- Authenticating with GitHub
√ Authenticating with GitHub
{
  "email": "...@...",
  "username": "bouiboui",
  ...
}
```
It worked! Awesome!

> @bouiboui if you're still having issues with saasify init on Windows, let's follow up on that in a separate issue.

Gotcha, unfortunately I think I will have to.

Thanks a lot for your time and for your fix!

**Comment by transitive-bullshit** [comment]
Great to hear -- as a workaround for now, `saasify init` just copies files from an existing example template, so you're welcome to just choose from one of the examples as a starting point.
