### ISSUE TITLE
Build API on Saasify and Contribute to it

### ISSUE THREAD

**Issue by CITGuru** [saasify-sh/saasify#17]
I really love the Saasify platform and would really love to build on it. I have a couple of APIs built on Python and Node, and would love to put it on Saasify.

The slack channel link is longer active, can I get a new link?

Also I would really love to contribute to Saasify and make it better.

**Comment by transitive-bullshit** [comment]
Awesome to hear @CITGuru!

Sorry about the link -- it should be updated now, but [here](https://join.slack.com/t/saasify/shared_invite/enQtODAxODA5MzU0NjczLTczOGU3NzNkYTJlMWIwZDkyNjJkOTk3MGEwZThlOWQyNTQxODZjZTExNjAzODJlZDQ3MWM5NWQwMGRiMDcyZTY) it is for reference.

Would love to setup some time to chat with you about what you're looking to build and how we could potentially collaborate together -- feel free to DM me in slack.

😄

**Comment by transitive-bullshit** [comment]
Closing as we connected on Slack.
