### ISSUE TITLE
Saasify Python Support

### ISSUE THREAD

**Issue by CITGuru** [saasify-sh/saasify#21]
Trying to write a simple saasify python project and test locally but i keep getting this error if I open the localhost url on browser:

```
Command failed: pip3 install --disable-pip-version-check --target . --upgrade werkzeug
Traceback (most recent call last):
  File "/usr/bin/pip3", line 9, in <module>
    from pip import main
ImportError: cannot import name 'main'
```

I think the issue is from `now-python` trying to installing something here: https://github.com/zeit/now/blob/canary/packages/now-python/src/index.ts#L28

Any fix to this. Also there should be a documentation on how to set it up with Python, virtualenv and so on.

**Comment by transitive-bullshit** [comment]
Hey @CITGuru, our Python support is very new and as you noted, we don't have any real docs on using Python at the moment.

As for Python dependencies, I would recommend locally using [pipenv](https://realpython.com/pipenv-guide/). They have a pretty solid guide that should help move you in the right direction.

The specific python error you're seeing I'm not familiar with, but I would love to follow up on this issue asap to resolve things.

Talk soon!

**Comment by CITGuru** [comment]
@transitive-bullshit Thanks for your response I fixed it with this url: https://gist.github.com/kogcyc/07c3e5d1f427c9fa6b99044d81f8ee82

**Comment by CITGuru** [comment]
@transitive-bullshit I will be putting up all errors, bugs I found while working with the Python version here.

Is there a way to specify auto-reload on save.

**Comment by chrisvxd** [comment]
@CITGuru we don't currently have auto-reload for `saasify dev`, but it's on our public roadmap: https://trello.com/c/5E5vl4Xv/59-add-caching-hot-reloading-to-saasify-dev-command

**Comment by mmedum** [comment]
Hi @CITGuru, I have a couple of examples using fastapi with saasify, one of them is: https://github.com/mmedum/climbing-grade-converter, this is also using pipenv for requirements. If you have any python questions, ping me here or join the saasify Slack workspace, then I will be happy to help :)

**Comment by CITGuru** [comment]
@chrisvxd I was able to use an asgi server to get over that. I am using uvicorn `uvicorn main:app --reload`. @mmedum Sure I will shoot you a message. I would also like to contribute to the python version.

**Comment by transitive-bullshit** [comment]
Hey @CITGuru, thanks a ton for trying out our early Python support.

We've fixed a lot of bugs in this area and released our first polished Python example publicly: [wordcloud](http://wordcloud.saasify.sh/) along with its [source code](https://github.com/saasify-sh/saasify/tree/master/examples/python/wordcloud).

We still need to add docs around the Python development process, but for now I'd recommend using `uvicorn main:app --reload` locally as you noted and then testing with `saasify dev` and finally `saasify deploy` once your project is working well locally.

I'm going to close this for now -- feel free to re-open or create another issue if you're still running into problems.

Thanks again!
