### ISSUE TITLE
Support for object binding patterns (object) arguments?

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [saasify-sh/saasify#49]
This works:

```ts
export default async (language: string): Promise<string> => {
    return "";
};
```

...but this doesn't:

```ts
type MySettings = { language: string; };
export default async ({ language }: MySettings): Promise<string> => {
    return "";
};
```

```
$ saasify dev
parsing config saasify.json
parsing service index.ts
Not implemented feature for syntax kind 'ObjectBindingPattern'.
```

For what it's worth, `ObjectBindingPattern` refers to capturing variables in an argument. [AST Explorer link](https://astexplorer.net/#/gist/6ffd3a492eaaaab3ef8d07ad1cc6aeb5/a89f173460a278ec60adbc89b082f428f68564c5)

**Comment by transitive-bullshit** [comment]
Definitely want to add support for this common use case.

Moving this issue over to https://github.com/transitive-bullshit/functional-typescript/issues/20

Thanks! 💯
