### ISSUE TITLE
[Feature Request]: Notify users if they're using an older version of the CLI

### ISSUE THREAD

**Issue by jamesgeorge007** [saasify-sh/saasify#63]
[update-notifier](https://www.npmjs.com/package/update-notifier) serves the purpose here. As from the tagline, `Inform users of your package of updates in a non-intrusive way`.

**Comment by jamesgeorge007** [comment]
@transitive-bullshit I would be happy to shoot up a PR on receiving the green signal :+1:

**Comment by transitive-bullshit** [comment]
@jamesgeorge007 that'd be awesome 😄
