### ISSUE TITLE
saasify.sh is not working (Secure Connection Failed)

### ISSUE THREAD

**Issue by moltar** [saasify-sh/saasify#8]
**In Firefox:**

Secure Connection Failed

An error occurred during a connection to saasify.xyz. Peer reports it experienced an internal error. Error code: SSL_ERROR_INTERNAL_ERROR_ALERT 

**In Chrome:**

This site can’t provide a secure connection
saasify.xyz sent an invalid response.
ERR_SSL_PROTOCOL_ERROR

**Comment by transitive-bullshit** [comment]
This should be resolved now.
